"""initial

Revision ID: 23b2dd6bde21
Revises: 9a9b9911bee5
Create Date: 2025-01-08 21:56:29.389399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b2dd6bde21'
down_revision = '9a9b9911bee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_username'), ['username'], unique=False)

    op.create_table('safes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combination', sa.String(length=20), nullable=False),
    sa.Column('prize', sa.String(length=255), nullable=False),
    sa.Column('donor', sa.String(length=100), nullable=False),
    sa.Column('reset_time', sa.DateTime(), nullable=False),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combination')
    )
    with op.batch_alter_table('safes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safes_reset_time'), ['reset_time'], unique=False)

    op.drop_table('safe')
    op.drop_table('attempt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('attempt', sa.VARCHAR(length=20), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('combination', sa.VARCHAR(length=20), nullable=False),
    sa.Column('prize', sa.VARCHAR(length=255), nullable=False),
    sa.Column('donor', sa.VARCHAR(length=100), nullable=False),
    sa.Column('reset_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safes_reset_time'))

    op.drop_table('safes')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_attempts_timestamp'))

    op.drop_table('attempts')
    # ### end Alembic commands ###
